# Generated by Django 5.2.1 on 2025-05-30 15:22

import cuid
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.CharField(default=cuid.cuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(choices=[(1, 'activo'), (2, 'inactivo'), (3, 'suspendido')], default=1)),
                ('nivel_programa', models.CharField(choices=[('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo')], default='tenologo', max_length=20)),
                ('duracion', models.IntegerField(help_text='Duración en horas')),
                ('modalidad', models.CharField(help_text='Modalidad del programa', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa')], max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='userAdmin',
            fields=[
                ('id', models.CharField(default=cuid.cuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(default=cuid.cuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('documento', models.CharField(choices=[('cc', 'CC'), ('nit', 'NIT')], default='cc', max_length=10)),
                ('numero_documento', models.IntegerField(max_length=12)),
                ('razon_social', models.CharField(default='sin razon social', max_length=150)),
                ('telefono', models.TextField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('actividad_economica', models.CharField(max_length=200)),
                ('estado', models.IntegerField(choices=[(1, 'activo'), (2, 'inactivo'), (3, 'suspendido')], default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
