# Generated by Django 5.2.1 on 2025-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_documento',
            field=models.IntegerField(),
        ),
    ]
