# Generated by Django 5.2.1 on 2025-05-31 06:11

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_empresa_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.CharField(default=cuid.cuid, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='programaformacion',
            name='id',
            field=models.CharField(default=cuid.cuid, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='id',
            field=models.CharField(default=cuid.cuid, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
