# Generated by Django 5.2.1 on 2025-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_empresa_id_alter_programaformacion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='correo_electronico',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='apellido',
            field=models.CharField(default='admin_sena_apellido', help_text='Apellido del administrador', max_length=100),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='nombre',
            field=models.CharField(default='admin_sena', help_text='Nombre del administrador', max_length=100),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
