# Generated by Django 5.2.1 on 2025-06-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_useradmin_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='documento',
            field=models.CharField(choices=[('cc', 'CC'), ('nit', 'NIT')], default='nit', max_length=10),
        ),
    ]
