# Generated by Django 5.2.1 on 2025-06-26 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_empresa_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='diagnosticos/')),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='Users.empresa')),
            ],
        ),
    ]
