# Generated by Django 5.2.1 on 2025-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_diagnosticoempresarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaformacion',
            name='nivel_programa',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo')], default='tecnologo', max_length=20),
        ),
    ]
