# Generated by Django 5.2.1 on 2025-08-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_passwordresetcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetcode',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
