# Generated by Django 5.2.1 on 2025-08-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_created_ad_passwordresetcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
